server:
  port: 9008
spring:
  application:
    name: tensquare-user #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.59.129:3306/tensquare_user?aharacterEncoding=UTF8&useSSL=false
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.59.129
  rabbitmq:
    host: 192.168.59.129

jwt:
  config:
    key: itcast
    ttl: 360000
